### ISSUE TITLE
Error when closing idea

### ISSUE THREAD

**Issue by AkromaPhage** [camel-idea-plugin/camel-idea-plugin#310]
Hi,

i recently upgraded Intellij to version 2017.2. 
When closing a project which does not depend on Camel a NullPointerException occurs.

The exception is 
`null
java.lang.NullPointerException
	at org.apache.camel.idea.CamelProjectComponent.disposeComponent(CamelProjectComponent.java:142)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.disposeComponents(ComponentManagerImpl.java:149)
	at com.intellij.openapi.project.impl.ProjectImpl.dispose(ProjectImpl.java:369)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:151)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
`

Camel plugin: 0.4.2
Intellij version: 2017.2 (172.3317.53)

Br,
Bernhard

**Comment by davsclaus** [comment]
Thanks for reporting. Do you get this exception every time you close IDEA or do you only see it once in a while?

**Comment by AkromaPhage** [comment]
Thank you for your fast response :)


I do see it every time i close the IDEA window.

Maybe this is also important:

I have 2 Projects opened (2 different Windows), one which has a dependency to camel and one which does not. When i close the project which is not dependent on camel, the error message appears in the project which is dependent on it

**Comment by davsclaus** [comment]
Thanks yes this is likely a reason why it happens when you have multiple projects and one with and without Camel. We have not yet upgraded to 2017.2 but will look into this when we get some time.

**Comment by fharms** [comment]
Fixed in #311
