### ISSUE TITLE
IOException: local history is broken and Recursive records found

### ISSUE THREAD

**Issue by bennetelli** [camel-idea-plugin/camel-idea-plugin#333]
Suddenly I'm getting this exception when running the integration-tests in intelliJ. When running these tests via console everything works fine :/

Any ideas?

ERROR: Local history is broken(version:6,current timestamp:12.10.2017 09:41:08,storage timestamp:12.10.2017 09:40:35,vfs timestamp:12.10.2017 09:40:35)
null
java.io.IOException: Recursive records found
	at com.intellij.history.core.ChangeListStorageImpl.a(ChangeListStorageImpl.java:280)
	at com.intellij.history.core.ChangeListStorageImpl.a(ChangeListStorageImpl.java:271)
	at com.intellij.history.core.ChangeListStorageImpl.purge(ChangeListStorageImpl.java:237)
	at com.intellij.history.core.ChangeList.purgeObsolete(ChangeList.java:175)
	at com.intellij.history.integration.LocalHistoryImpl.a(LocalHistoryImpl.java:127)
	at com.intellij.history.integration.LocalHistoryImpl.c(LocalHistoryImpl.java:73)
	at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:60)
	at java.lang.Thread.run(Thread.java:748)
ERROR: Local history is broken(version:6,current timestamp:12.10.2017 09:41:08,storage timestamp:12.10.2017 09:40:35,vfs timestamp:12.10.2017 09:40:35)
null
java.lang.AssertionError: Local history is broken(version:6,current timestamp:12.10.2017 09:41:08,storage timestamp:12.10.2017 09:40:35,vfs timestamp:12.10.2017 09:40:35)
null
	at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:61)
	at com.intellij.testFramework.TestLogger.error(TestLogger.java:40)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:154)
	at com.intellij.history.core.ChangeListStorageImpl.a(ChangeListStorageImpl.java:110)
	at com.intellij.history.core.ChangeListStorageImpl.purge(ChangeListStorageImpl.java:250)
	at com.intellij.history.core.ChangeList.purgeObsolete(ChangeList.java:175)
	at com.intellij.history.integration.LocalHistoryImpl.a(LocalHistoryImpl.java:127)
	at com.intellij.history.integration.LocalHistoryImpl.c(LocalHistoryImpl.java:73)
	at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:60)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Recursive records found
	at com.intellij.history.core.ChangeListStorageImpl.a(ChangeListStorageImpl.java:280)
	at com.intellij.history.core.ChangeListStorageImpl.a(ChangeListStorageImpl.java:271)
	at com.intellij.history.core.ChangeListStorageImpl.purge(ChangeListStorageImpl.java:237)
	... 5 more
Exception in thread "Shutdown tracker" java.lang.AssertionError: Local history is broken(version:6,current timestamp:12.10.2017 09:41:08,storage timestamp:12.10.2017 09:40:35,vfs timestamp:12.10.2017 09:40:35)
null
	at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:61)
	at com.intellij.testFramework.TestLogger.error(TestLogger.java:40)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:158)
	at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:63)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: Local history is broken(version:6,current timestamp:12.10.2017 09:41:08,storage timestamp:12.10.2017 09:40:35,vfs timestamp:12.10.2017 09:40:35)
null
	at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:61)
	at com.intellij.testFramework.TestLogger.error(TestLogger.java:40)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:154)
	at com.intellij.history.core.ChangeListStorageImpl.a(ChangeListStorageImpl.java:110)
	at com.intellij.history.core.ChangeListStorageImpl.purge(ChangeListStorageImpl.java:250)
	at com.intellij.history.core.ChangeList.purgeObsolete(ChangeList.java:175)
	at com.intellij.history.integration.LocalHistoryImpl.a(LocalHistoryImpl.java:127)
	at com.intellij.history.integration.LocalHistoryImpl.c(LocalHistoryImpl.java:73)
	at com.intellij.openapi.util.ShutDownTracker.run(ShutDownTracker.java:60)
	... 1 more
Caused by: java.io.IOException: Recursive records found
	at com.intellij.history.core.ChangeListStorageImpl.a(ChangeListStorageImpl.java:280)
	at com.intellij.history.core.ChangeListStorageImpl.a(ChangeListStorageImpl.java:271)
	at com.intellij.history.core.ChangeListStorageImpl.purge(ChangeListStorageImpl.java:237)
	... 5 more

**Comment by fharms** [comment]
try to delete the local cache directory, if you working under OS X look for /Users/<user>/Library/Caches/IdeaIC<version>/plugins-sandbox/

**Comment by bennetelli** [comment]
Thanks so much! Will create a FAQ page and add this question/solution to it
